In [3]:
import numpy as np
a = np.ones(256)
b = np.ones([256,3])

In [6]:
a * b

ValueError: operands could not be broadcast together with shapes (256,) (256,3) 

In [12]:
c = np.ones(1)
d = np.ones(3)

In [11]:
c, d

(array([1., 1., 1.]), array([1., 1., 1.]))

In [15]:
np.dot(c,d[:1])

1.0

In [24]:
np.dot(1,d[2:])

array([1.])

In [23]:
c

array([1.])