In [1]:
import tensorflow as tf

In [22]:
w = tf.Variable([[1.0]])


In [23]:
w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>

In [24]:
with tf.GradientTape() as tape:
    loss = w * w

In [20]:
tf.GradientTape()

In [9]:
grad = tape.gradient(loss, w)

In [25]:
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [11]:
tape

In [21]:
tape.gradient(loss, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [26]:
print(grad) 

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [27]:
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

loss_history = []


In [28]:
def train_step(images, labels):
    with tf.GradientTape() as tape:
        logits = mnist_model(images, training=True)

        # Add asserts to check the shape of the output.
        tf.debugging.assert_equal(logits.shape, (32, 10))

        loss_value = loss_object(labels, logits)

    loss_history.append(loss_value.numpy().mean())
    grads = tape.gradient(loss_value, mnist_model.trainable_variables)
    optimizer.apply_gradients(zip(grads, mnist_model.trainable_variables))


In [ ]:
class Sinusoid(tf.keras.Model):
    def __init__(self):
        super(Sinusoid, self).__init__()
        #self.W = tf.Variable(5., name='weight')
        #self.B = tf.Variable(10., name='bias')
        self.A = tf.Variable(20., name='Amplitude')
        self.B = tf.Variable(.25, name='Period')
        self.C = tf.Variable(1., name='Intercept')
        self.D = tf.Variable(2., name='PhaseShift')
        
    
    def call(self, time, volume):
        bare_sine = tf.Sin()
        
        return sine_value # inputs * self.W + self.B

    


In [ ]:
A = tf.Variable(20., name='Amplitude')
B = tf.Variable(.25, name='Period')
C = tf.Variable(1., name='Intercept')
D = tf.Variable(2., name='PhaseShift')

with tf.GradientTape(watch_accessed_variables=False) as tape:
    # tape.watch(x1)
    y0 = tf.math.sin()
    y1 = tf.nn.softplus(x1)
    y = y0 + y1
    ys = tf.reduce_sum(y)

In [ ]:
class Dense(tf.Module):
  def __init__(self, in_features, out_features, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(
      tf.random.normal([in_features, out_features]), name='w')
    self.b = tf.Variable(tf.zeros([out_features]), name='b')
  def __call__(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)

class SequentialModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

    self.dense_1 = Dense(in_features=3, out_features=3)
    self.dense_2 = Dense(in_features=3, out_features=2)

  def __call__(self, x):
    x = self.dense_1(x)
    return self.dense_2(x)

# You have made a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))