# 4.5 LSTM Model Testing
Reverse train and test sets to ensure data accuracy. 

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [2]:
y = np.load('./data/prepared/august25screenfixed/numpy_matrices/y_br.npy')

In [3]:
y.shape

(30, 4000)

In [4]:
y_train = y[:, :2000]
y_test = y[:, 2000:]

y_train.shape, y_test.shape

((30, 2000), (30, 2000))

In [5]:
y_train = y_train.reshape([60000, 1])
y_test = y_test.reshape([60000, 1])
y_train.shape, y_test.shape

((60000, 1), (60000, 1))

In [25]:
y_train

array([[ 0.00070822],
       [ 0.00212917],
       [-0.00141743],
       ...,
       [-0.00033146],
       [ 0.00099338],
       [-0.00039719]])

In [6]:
X_train = np.load('./data/prepared/august25screenfixed/numpy_matrices/X_train.npy')
X_test = np.load('./data/prepared/august25screenfixed/numpy_matrices/X_test.npy')

In [7]:
X_train.shape, X_test.shape

((60000, 1, 116, 60), (60000, 1, 116, 60))

In [8]:
X_train = X_train[:,:,:,:10]
X_train.shape

(60000, 1, 116, 10)

In [9]:
X_train.shape = (60000, 116, 10)
X_train.shape

(60000, 116, 10)

In [10]:
X_test = X_test[:,:,:,:10]
X_test.shape = (60000, 116, 10)
X_test.shape

(60000, 116, 10)

In [11]:
Xr_tp = np.transpose(X_train, axes=(0,2,1))
Xr_tp.shape

(60000, 10, 116)

In [12]:
Xe_tp = np.transpose(X_test, axes=(0,2,1))
Xe_tp.shape

(60000, 10, 116)

In [13]:
yr_d = y_train.copy()
yr_d[np.where(yr_d > 0)] = 1
yr_d[np.where(yr_d < 0)] = 0
np.unique(yr_d, return_counts=True)

(array([0., 1.]), array([32831, 27169]))

In [14]:
ye_d = y_test.copy()
ye_d[np.where(ye_d > 0)] = 1
ye_d[np.where(ye_d < 0)] = 0
np.unique(ye_d, return_counts=True)

(array([0., 1.]), array([33401, 26599]))

In [27]:
#Xe_tp == Xr_tp

#### LSTM Testing

In [15]:
model = keras.Sequential([
    keras.layers.LSTM(10),
    keras.layers.Dense(2, activation='softmax')
    
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(Xe_tp, ye_d, epochs=100,
         validation_data=(Xr_tp, yr_d))

Train on 60000 samples, validate on 60000 samples
Epoch 1/100
60000/60000 [==============================] - 26s 429us/sample - loss: 0.6849 - accuracy: 0.5555 - val_loss: 0.6875 - val_accuracy: 0.5472
Epoch 2/100
60000/60000 [==============================] - 22s 365us/sample - loss: 0.6829 - accuracy: 0.5548 - val_loss: 0.6840 - val_accuracy: 0.5471
Epoch 3/100
60000/60000 [==============================] - 22s 373us/sample - loss: 0.6816 - accuracy: 0.5555 - val_loss: 0.6861 - val_accuracy: 0.5473
Epoch 4/100
60000/60000 [==============================] - 21s 354us/sample - loss: 0.6808 - accuracy: 0.5572 - val_loss: 0.6830 - val_accuracy: 0.5490
Epoch 5/100
60000/60000 [==============================] - 22s 364us/sample - loss: 0.6801 - accuracy: 0.5591 - val_loss: 0.6820 - val_accuracy: 0.5480
Epoch 6/100
60000/60000 [==============================] - 22s 363us/sample - loss: 0.6780 - accuracy: 0.5676 - val_loss: 0.6808 - val_accuracy: 0.5642
Epoch 7/100
60000/60000 [=============

60000/60000 [==============================] - 20s 326us/sample - loss: 0.3934 - accuracy: 0.9151 - val_loss: 0.3902 - val_accuracy: 0.9189
Epoch 55/100
60000/60000 [==============================] - 20s 326us/sample - loss: 0.3925 - accuracy: 0.9161 - val_loss: 0.4050 - val_accuracy: 0.9026
Epoch 56/100
60000/60000 [==============================] - 20s 328us/sample - loss: 0.3917 - accuracy: 0.9165 - val_loss: 0.4202 - val_accuracy: 0.8835
Epoch 57/100
60000/60000 [==============================] - 20s 333us/sample - loss: 0.3890 - accuracy: 0.9195 - val_loss: 0.4014 - val_accuracy: 0.9058
Epoch 58/100
60000/60000 [==============================] - 18s 292us/sample - loss: 0.3891 - accuracy: 0.9201 - val_loss: 0.3947 - val_accuracy: 0.9143
Epoch 59/100
60000/60000 [==============================] - 16s 261us/sample - loss: 0.3883 - accuracy: 0.9210 - val_loss: 0.3936 - val_accuracy: 0.9146
Epoch 60/100
60000/60000 [==============================] - 17s 289us/sample - loss: 0.3887 - a

In [16]:
#model.save_weights('./data/Models/1min91acc_010920')

In [17]:
#model.save('./data/Models/1min91acc_010920') 

In [18]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(Xr_tp, yr_d, epochs=20,
         validation_data=(Xe_tp, ye_d))

Train on 60000 samples, validate on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 26s 426us/sample - loss: 0.3747 - accuracy: 0.9351 - val_loss: 0.3595 - val_accuracy: 0.9529
Epoch 2/20
60000/60000 [==============================] - 21s 353us/sample - loss: 0.3706 - accuracy: 0.9402 - val_loss: 0.3584 - val_accuracy: 0.9543
Epoch 3/20
60000/60000 [==============================] - 21s 343us/sample - loss: 0.3691 - accuracy: 0.9418 - val_loss: 0.3600 - val_accuracy: 0.9522
Epoch 4/20
60000/60000 [==============================] - 24s 399us/sample - loss: 0.3678 - accuracy: 0.9439 - val_loss: 0.3625 - val_accuracy: 0.9488
Epoch 5/20
60000/60000 [==============================] - 20s 335us/sample - loss: 0.3671 - accuracy: 0.9438 - val_loss: 0.3589 - val_accuracy: 0.9533
Epoch 6/20
60000/60000 [==============================] - 21s 345us/sample - loss: 0.3666 - accuracy: 0.9447 - val_loss: 0.3592 - val_accuracy: 0.9531
Epoch 7/20
60000/60000 [====================

In [19]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(Xr_tp, yr_d, epochs=20,
         validation_data=(Xe_tp, ye_d))

Train on 60000 samples, validate on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 24s 403us/sample - loss: 0.3593 - accuracy: 0.9536 - val_loss: 0.3561 - val_accuracy: 0.9569
Epoch 2/20
60000/60000 [==============================] - 22s 360us/sample - loss: 0.3591 - accuracy: 0.9542 - val_loss: 0.3566 - val_accuracy: 0.9562
Epoch 3/20
60000/60000 [==============================] - 21s 346us/sample - loss: 0.3590 - accuracy: 0.9542 - val_loss: 0.3560 - val_accuracy: 0.9571
Epoch 4/20
60000/60000 [==============================] - 22s 360us/sample - loss: 0.3590 - accuracy: 0.9542 - val_loss: 0.3561 - val_accuracy: 0.9569
Epoch 5/20
60000/60000 [==============================] - 21s 350us/sample - loss: 0.3589 - accuracy: 0.9542 - val_loss: 0.3562 - val_accuracy: 0.9567
Epoch 6/20
60000/60000 [==============================] - 20s 333us/sample - loss: 0.3589 - accuracy: 0.9548 - val_loss: 0.3563 - val_accuracy: 0.9567
Epoch 7/20
60000/60000 [====================

In [20]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.000001),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(Xr_tp, yr_d, epochs=20,
         validation_data=(Xe_tp, ye_d))

Train on 60000 samples, validate on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 19s 311us/sample - loss: 0.3581 - accuracy: 0.9556 - val_loss: 0.3560 - val_accuracy: 0.9570
Epoch 2/20
60000/60000 [==============================] - 17s 282us/sample - loss: 0.3581 - accuracy: 0.9556 - val_loss: 0.3560 - val_accuracy: 0.9567
Epoch 3/20
60000/60000 [==============================] - 18s 295us/sample - loss: 0.3581 - accuracy: 0.9558 - val_loss: 0.3560 - val_accuracy: 0.9568
Epoch 4/20
60000/60000 [==============================] - 18s 292us/sample - loss: 0.3581 - accuracy: 0.9557 - val_loss: 0.3561 - val_accuracy: 0.9567
Epoch 5/20
60000/60000 [==============================] - 20s 341us/sample - loss: 0.3581 - accuracy: 0.9557 - val_loss: 0.3560 - val_accuracy: 0.9568
Epoch 6/20
60000/60000 [==============================] - 22s 372us/sample - loss: 0.3581 - accuracy: 0.9557 - val_loss: 0.3561 - val_accuracy: 0.9568
Epoch 7/20
60000/60000 [====================

In [21]:
model.save('./data/Models/1min95acc_030920') 

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: ./data/Models/1min95acc_030920/assets


In [36]:
model.save_weights('./data/Models/1min95acc_030920_weights')

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  multiple                  5080      
_________________________________________________________________
dense (Dense)                multiple                  22        
Total params: 5,102
Trainable params: 5,102
Non-trainable params: 0
_________________________________________________________________


In [38]:
model = keras.models.load_model('./data/Models/1min95acc_030920')

In [39]:
preds = model.predict(Xr_tp)
y_preds = np.argmax(preds, axis=1)

y_true = yr_d.reshape(60000)

In [40]:
from sklearn.metrics import accuracy_score

accuracy_score(y_true, y_preds)

0.95575

In [41]:
preds = model.predict(Xe_tp)
y_preds = np.argmax(preds, axis=1)

y_true = ye_d.reshape(60000)

accuracy_score(y_true, y_preds)

0.9567666666666667

In [42]:
Xr_tp.shape

(60000, 10, 116)